version: '3.9'

services:
  islamic-dreams-frontend:
    image: islamic-dreams:1.0.0
    build:
      context: ../frontend
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "3001:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../frontend/.env.production
    networks:
      - app-network

  islamic-dreams-admin:
    image: islamic-dreams-admin:1.0.0
    build:
      context: ../admin-panel
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "3002:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../admin-panel/.env.production
    networks:
      - app-network

  islamic-dreams-api:
    image: islamic-dreams-api:1.0.0
    build:
      context: ../api-service
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "5050:5050"
    env_file:
      - ../api-service/.env.production
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    volumes:
      - /islamic-dreams/data:/data/db
      - /islamic-dreams/backup:/backup
    networks:
      - app-network
    ports:
      - "27317:27017"
  #    restart: always

networks:
  app-network:
    driver: bridge
