import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import {AuthProvider} from "@/contexts/AuthContexts";
import {ChatProvider} from "@/components/getStream/chat/ChatContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin - Ruqya",
  description: "Generated by create next app",
    icons: {
        icon: '/logo-icon.png',
        shortcut: '/logo-icon.png',
        apple: '/logo-icon.png',
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
      {/*<SessionProvider>{children}</SessionProvider>*/}
      <AuthProvider>
          <ChatProvider >
          {children}
          <Toaster />
          </ChatProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
